management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
feign:
  hystrix:
    enabled: true
  clients:
    withTls: true
  secrets:
    trustStoreResource: "/trust.jks"
    keyStoreResource:
    keyStorePassword:

hystrix:
  command:
    HttpStatClient#get200(Integer):
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
      circuitBreaker:
        requestVolumeThreshold: 2
        sleepWindowInMilliseconds: 60000
    HttpStatClient#get400(Integer):
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
      circuitBreaker:
        requestVolumeThreshold: 2
        sleepWindowInMilliseconds: 60000

httpStatClient:
  name: "httpStatClient"
  url: "https://httpstat.us"
